
default:
	./jemdoc.py -o ../ home.jemdoc
	./jemdoc.py -o ../ biography.jemdoc
	./jemdoc.py -o ../ research.jemdoc
	./jemdoc.py -o ../ publications.jemdoc
	./jemdoc.py -o ../ teaching-past.jemdoc
	./jemdoc.py -o ../ teaching-current.jemdoc

