
default:
	./jemdoc.py -o ../ index.jemdoc
	./jemdoc.py -o ../ biography.jemdoc
	./jemdoc.py -o ../ publications.jemdoc
	./jemdoc.py -o ../ team.jemdoc
	./jemdoc.py -o ../ courses.jemdoc
	./jemdoc.py -o ../ recommendation-letters.jemdoc

